server:
  #by default config server runs on port 8888
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaibhavg12/demo-config-store
          search-paths:
            - '*service'
          # in case your config store is a private repo, then provide username and password
          # username: root
          # passphrase: 12345